---
- hosts: all
  become: yes
  gather_facts: yes 
  tasks:

    - name: Update all packages to their latest version
      ansible.builtin.apt:
         name: "*"
         state: latest

    - name: Creating an empty file
      file:
         path: "/home/deploy/money"
         state: touch
    
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/deploy/devops
        state: directory
        mode: '0755'
    
    - name: Install the package "ansible joel"
      apt:
        name: ansible
        state: present
