---
- hosts: all     ###### "all" means running this script in all your host #########
  become: yes
  gather_facts: yes 
  tasks:

    - name: Update all packages to their latest version         ####module1####
      ansible.builtin.apt:
         name: "*"
         state: latest

    - name: Creating an empty file                          ####module2####
      file:
         path: "/home/nesdeploy/money"
         state: touch
    
    - name: Create a directory if it does not exist             ####module3####
      ansible.builtin.file:
        path: /home/nesdeploy/devops
        state: directory
        mode: '0755'
    
    - name: Install the package "ansible nestor"                  ####module4####
      apt:
        name: ansible
        state: present



### commands : ansible-playbook playbook.yml -i host.yml
